# Generated by Django 2.2.6 on 2020-05-20 06:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='filext',
            field=models.FileField(default='', upload_to='%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'], message='必须是图像文件')]),
        ),
        migrations.AlterField(
            model_name='file',
            name='auther',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='文件所属'),
        ),
    ]
