# Generated by Django 2.2.6 on 2020-05-20 06:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0002_auto_20200520_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='filedata',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间'),
        ),
    ]
