# Generated by Django 2.2.6 on 2020-05-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0003_auto_20200520_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='filext',
        ),
    ]
