# Generated by Django 2.2.6 on 2020-05-20 07:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('code_audit', '0006_auto_20200520_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='auther',
        ),
    ]
